### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by yerim8373** [KCC-javaminiproject/NeoBis#5]
## Issue : ✅ FEATURE
> Account, Customer, Trade

## Desciption
> Account, Customer, Trade 클래스 작성

## Todo
- [x] Account 클래스 작성
- [x] Customer 클래스 작성
- [x] Trade 클래스 작성

## ETC
> 기타사항
